swagger: '2.0'
info:
  title: Swagger Documentation Rails Example
  description: An example of setting up Swagger Documentation for a Rails application
  version: 1.0.0
basePath: /
produces:
  - application/json
paths:
  $include:
    - paths/payments/calculate.yaml

definitions:
  BadRequestResponse:
    description: Required parameters are missing or invalid.
    properties:
      message:
        type: string
        description: Error message

  RequestTimeoutResponse:
    description: The request timed out.

  $include:
    - definitions/payments/calculate.yaml
    - definitions/payments/response.yaml